apiVersion: v1
kind: Service
metadata:
  name: my-devops-app-service
  namespace: production
spec:
  selector:
    app: my-devops-app
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
